spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true




end-point:
  szs-code-test: https://codetest.3o3.co.kr

jwt:
  secret-key: bbackjk
  expired-minutes: 30

encrypt-key: bbackjkencryptkeyyy